// Generators for a workspace bundle. The output has the same shape as the
// hand-written WadSpaces/containers/<id>/ directories:
//
//   Dockerfile  docker-compose.yml  README.md  wad-<id>.container  workspaces.yaml.snippet
//   root/etc/wadspaces/repos.list
//   root/etc/wadspaces/kalebrowser-resources.json   (Kale Browser apps only)
//   root/usr/share/backgrounds/wallpaper.<ext>      (when a wallpaper is set)
//
// and builds with `containers/build.sh --only <id>` after copying it into
// WadSpaces/containers/<id>/.

import { type CreatorSpec, type WaddSpec, resolveFeatures, toWaddSpec, volumesFor } from "../lib/spec";

const q = (s: string) => `"${s.replace(/(["\\$`])/g, "\\$1")}"`;

export function dockerfile(spec: CreatorSpec): string {
  const features = resolveFeatures(spec);
  const kale = spec.kaleResources.length > 0;
  const lines: string[] = [
    `# ${spec.name} workspace. Generated by Wad Creator.`,
    `ARG BASE_IMAGE=${spec.baseImage}`,
    "FROM ${BASE_IMAGE}",
    "",
  ];
  if (kale) lines.push("ARG KALEBROWSER_REF=main");
  const env = [`TITLE=${q(spec.name)}`];
  if (spec.wallpaper) {
    env.push(`WALLPAPER=${q(`/usr/share/backgrounds/${spec.wallpaper.fileName}`)}`);
    if (spec.wallpaper.mode !== "center") env.push(`WALLPAPER_MODE=${spec.wallpaper.mode}`);
    if (spec.wallpaper.color !== "#0b0b14") env.push(`WALLPAPER_COLOR=${q(spec.wallpaper.color)}`);
  }
  lines.push(env.length === 1 ? `ENV ${env[0]}` : `ENV ${env.join(" \\\n    ")}`, "");
  if (features.length) lines.push(`RUN wadspaces-feature ${features.join(" ")}`, "");
  if (spec.webapps.length) {
    lines.push(
      "RUN " + spec.webapps.map((w) => `wadspaces-webapp ${q(w.name)} ${w.url}`).join(" && \\\n    "),
      "",
    );
  }
  lines.push("COPY root/ /");
  if (kale) {
    lines.push(
      "",
      'RUN wadspaces-kalebrowser-install --ref "${KALEBROWSER_REF}" \\',
      "      --resources /etc/wadspaces/kalebrowser-resources.json",
    );
  }
  return lines.join("\n") + "\n";
}

export function reposList(spec: CreatorSpec): string {
  const rows = spec.repos.map((r) =>
    [r.url, r.dest || r.url.replace(/\.git$/, "").split("/").pop(), r.postClone].filter(Boolean).join(" "),
  );
  return ["# <url> <folder on the Desktop> [one-time post-clone command]", ...rows].join("\n") + "\n";
}

export function kaleResourcesJson(spec: CreatorSpec): string {
  return JSON.stringify(spec.kaleResources, null, 4) + "\n";
}

export function compose(spec: CreatorSpec): string {
  const env = Object.entries(spec.env).map(([k, v]) => `      - ${k}=${v}`);
  const vols = volumesFor(spec);
  const out = [
    "---",
    `# ${spec.name} workspace. Generated by Wad Creator. Normally started by wadd;`,
    "# this file is for building and running it by hand:",
    `#   ../build.sh --only ${spec.id} && podman-compose up -d`,
    `# then open http://127.0.0.1:${spec.port}`,
  ];
  if (spec.secrets.length) {
    out.push("secrets:");
    for (const s of spec.secrets) out.push(`  ${s}:`, "    external: true");
  }
  if (vols.length) {
    out.push("", "volumes:");
    for (const v of vols) out.push(`  ${v.split(":")[0]}:`);
  }
  out.push(
    "",
    "services:",
    `  ${spec.id}:`,
    `    image: ${spec.image}`,
    `    container_name: wad-${spec.id}`,
    "    labels:",
    `      wadspaces.id: ${spec.id}`,
  );
  if (env.length) out.push("    environment:", ...env);
  if (spec.secrets.length) out.push("    secrets:", ...spec.secrets.map((s) => `      - ${s}`));
  if (vols.length) out.push("    volumes:", ...vols.map((v) => `      - ${v}`));
  if (spec.devices.length) out.push("    devices:", ...spec.devices.map((d) => `      - ${d}:${d}`));
  out.push("    ports:", `      - 127.0.0.1:${spec.port}:3000`);
  if (spec.shmSize) out.push(`    shm_size: "${spec.shmSize}b"`);
  out.push('    restart: "no"');
  return out.join("\n") + "\n";
}

/** Byte-identical to Workspace-Switcher/wadd/quadlet.py render_container_unit(). */
export function quadlet(w: WaddSpec): string {
  const lines = [
    "# Generated by `wadd gen-quadlets` from workspaces.yaml. Do not edit.",
    "[Unit]",
    `Description=WadSpaces workspace: ${w.name}`,
    "Wants=network-online.target",
    "After=network-online.target",
    "",
    "[Container]",
    `Image=${w.image}`,
    `ContainerName=${w.container_name || `wad-${w.id}`}`,
    `Label=wadspaces.id=${w.id}`,
    `PublishPort=127.0.0.1:${w.port}:${w.container_port ?? 3000}`,
  ];
  const env = w.env ?? {};
  for (const k of Object.keys(env).sort()) lines.push(`Environment=${k}=${env[k]}`);
  for (const s of w.secrets ?? []) lines.push(`Secret=${s}`);
  for (const v of w.volumes ?? []) lines.push(`Volume=${v}`);
  for (const d of w.devices ?? []) lines.push(`AddDevice=${d}`);
  if (w.shm_size) lines.push(`ShmSize=${w.shm_size}`);
  lines.push(
    "Pull=missing",
    "",
    "[Service]",
    "Restart=no",
    "TimeoutStartSec=900",
    "",
    "# No [Install] section: wadd starts this unit on the first switch.",
    "",
  );
  return lines.join("\n");
}

function yamlScalar(v: unknown): string {
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  const s = String(v);
  return /^[A-Za-z0-9_./@-][A-Za-z0-9_./@:-]*$/.test(s) && !/^(true|false|null|yes|no|\d+)$/i.test(s)
    ? s
    : JSON.stringify(s);
}

export function workspacesYamlSnippet(w: WaddSpec): string {
  const out = [`  - id: ${w.id}`];
  for (const [k, v] of Object.entries(w)) {
    if (k === "id" || v == null) continue;
    if (Array.isArray(v)) {
      if (v.length) out.push(`    ${k}: [${v.map(yamlScalar).join(", ")}]`);
    } else if (typeof v === "object") {
      const entries = Object.entries(v as Record<string, string>);
      if (entries.length) {
        out.push(`    ${k}:`);
        for (const [ek, ev] of entries) out.push(`      ${ek}: ${JSON.stringify(ev)}`);
      }
    } else {
      out.push(`    ${k}: ${yamlScalar(v)}`);
    }
  }
  return out.join("\n") + "\n";
}

export function readme(spec: CreatorSpec): string {
  const features = resolveFeatures(spec);
  return `# ${spec.name}

Generated by Wad Creator.

| | |
|---|---|
| Features | ${features.join(", ") || "none"} |
| Repos | ${spec.repos.map((r) => r.url).join("<br>") || "none"} |
| Web apps | ${spec.webapps.map((w) => w.name).join(", ") || "none"} |
| Kale Browser apps | ${spec.kaleResources.map((k) => k.app_name).join(", ") || "none"} |
| Port | 127.0.0.1:${spec.port} |
| Hotkey | ${spec.hotkey ? `Super+${spec.hotkey}` : "none"} |

## Build

Copy this folder to \`WadSpaces/containers/${spec.id}/\`, then:

\`\`\`bash
cd WadSpaces/containers
./build.sh --only ${spec.id}          # add --kalebrowser-local to use ../KaleBrowser
\`\`\`

## Run

On a WadSpaces machine, "Install on this machine" in Wad Creator adds it to
\`/etc/wadspaces/workspaces.yaml\`. By hand, add \`workspaces.yaml.snippet\` to
that file, or use \`wad-${spec.id}.container\` directly as a quadlet.

To try it without the switcher:

\`\`\`bash
podman-compose up -d && xdg-open http://127.0.0.1:${spec.port}
\`\`\`
${spec.secrets.length ? `\nSecrets it expects (create them with \`printf '%s' VALUE | podman secret create NAME -\`): ${spec.secrets.join(", ")}\n` : ""}`;
}

export interface BundleFile {
  path: string;
  content: string | Uint8Array;
}

export function bundleFiles(spec: CreatorSpec, wallpaper?: Uint8Array): BundleFile[] {
  const w = toWaddSpec(spec);
  const files: BundleFile[] = [
    { path: "Dockerfile", content: dockerfile(spec) },
    { path: "docker-compose.yml", content: compose(spec) },
    { path: "README.md", content: readme(spec) },
    { path: `wad-${spec.id}.container`, content: quadlet(w) },
    { path: "workspaces.yaml.snippet", content: workspacesYamlSnippet(w) },
    { path: "root/etc/wadspaces/repos.list", content: reposList(spec) },
  ];
  if (spec.kaleResources.length) {
    files.push({ path: "root/etc/wadspaces/kalebrowser-resources.json", content: kaleResourcesJson(spec) });
  }
  if (spec.wallpaper && wallpaper) {
    files.push({ path: `root/usr/share/backgrounds/${spec.wallpaper.fileName}`, content: wallpaper });
  }
  return files;
}

export async function bundleZip(spec: CreatorSpec, wallpaper?: Uint8Array): Promise<Blob> {
  const { default: JSZip } = await import("jszip");
  const zip = new JSZip();
  const dir = zip.folder(spec.id)!;
  for (const f of bundleFiles(spec, wallpaper)) dir.file(f.path, f.content);
  return zip.generateAsync({ type: "blob" });
}
