// Generators for a workspace bundle. The output has the same shape as the
// hand-written Wadspaces-David/<dir>/ directories:
//
//   Dockerfile  docker-compose.yml  README.md  wad-<id>.container  workspaces.yaml.snippet
//   root/etc/wadspaces/layout.json                  (Builder desktops: icons in order)
//   root/etc/wadspaces/kalebrowser-resources.json   (Kale Browser apps only)
//   root/usr/share/backgrounds/wallpaper.<ext>      (when a wallpaper is set)
//
// and builds with `Wadspaces-David/build.sh --only <id>` after copying it into
// Wadspaces-David/<id>/, or through wadd on the machine. Project files are
// never in it: wadd mounts the project folders when it launches the wadspace.

import { layoutJson } from "../build";
import { type CreatorSpec, type WaddSpec, displayOf, resolveFeatures, toWaddSpec, volumesFor } from "../spec";

const q = (s: string) => `"${s.replace(/(["\\$`])/g, "\\$1")}"`;

export function dockerfile(spec: CreatorSpec): string {
  const features = resolveFeatures(spec);
  const kale = spec.kaleResources.length > 0;
  const lines: string[] = [
    `# ${spec.name} workspace. Generated by Wad Creator.`,
    `ARG BASE_IMAGE=${spec.baseImage}`,
    "FROM ${BASE_IMAGE}",
    "",
  ];
  if (kale) lines.push("ARG KALEBROWSER_REF=main");
  const env = [`TITLE=${q(spec.name)}`];
  if (spec.wallpaper) {
    env.push(`WALLPAPER=${q(`/usr/share/backgrounds/${spec.wallpaper.fileName}`)}`);
    if (spec.wallpaper.mode !== "center") env.push(`WALLPAPER_MODE=${spec.wallpaper.mode}`);
    if (spec.wallpaper.color !== "#0b0b14") env.push(`WALLPAPER_COLOR=${q(spec.wallpaper.color)}`);
  }
  lines.push(env.length === 1 ? `ENV ${env[0]}` : `ENV ${env.join(" \\\n    ")}`, "");
  if (features.length) lines.push(`RUN wadspaces-feature ${features.join(" ")}`, "");
  const apt = spec.aptApps ?? [];
  if (apt.length) {
    // One RUN: apt's lists are fetched once, and --clean drops them from the layer.
    lines.push(
      "RUN " +
        [...apt.map((a) => ["wadspaces-apt", a.id, ...(a.desktop ? ["--desktop", a.desktop] : []), ...a.packages].join(" ")), "wadspaces-apt --clean"].join(
          " && \\\n    ",
        ),
      "",
    );
  }
  if (spec.webapps.length) {
    lines.push(
      "RUN " +
        spec.webapps.map((w) => `wadspaces-webapp ${w.id ? `--id ${w.id} ` : ""}${q(w.name)} ${w.url}`).join(" && \\\n    "),
      "",
    );
  }
  lines.push("COPY root/ /");
  if (kale) {
    lines.push(
      "",
      'RUN wadspaces-kalebrowser-install --ref "${KALEBROWSER_REF}" \\',
      "      --resources /etc/wadspaces/kalebrowser-resources.json",
    );
  }
  return lines.join("\n") + "\n";
}

export function kaleResourcesJson(spec: CreatorSpec): string {
  return JSON.stringify(spec.kaleResources, null, 4) + "\n";
}

// A native (display: host) workspace runs remotely as two containers: the
// workspace and the stream sidecar it draws on (see Wadspaces-David/_stream). A
// streamed one is a single all-in-one Selkies container.
export function compose(spec: CreatorSpec): string {
  const env = Object.entries(spec.env).map(([k, v]) => `      - ${k}=${v}`);
  const lean = displayOf(spec) === "host";
  const displayVol = `${spec.id}-display`;
  const vols = volumesFor(spec);
  const out = lean
    ? [
        "---",
        `# ${spec.name} workspace, run remotely: the workspace plus the stream`,
        "# sidecar that shows it in a browser. Generated by Wad Creator. On a",
        "# WadSpaces machine wadd runs the same image on the screen instead.",
        `#   ../build.sh --only ${spec.id} --run`,
        `# then open http://127.0.0.1:${spec.port}`,
      ]
    : [
        "---",
        `# ${spec.name} workspace. Generated by Wad Creator. Normally started by wadd;`,
        "# this file is for building and running it by hand:",
        `#   ../build.sh --only ${spec.id} && podman-compose up -d`,
        `# then open http://127.0.0.1:${spec.port}`,
      ];
  if (spec.secrets.length) {
    out.push("secrets:");
    for (const s of spec.secrets) out.push(`  ${s}:`, "    external: true");
  }
  if (vols.length || lean) {
    out.push("", "volumes:");
    for (const v of vols) out.push(`  ${v.split(":")[0]}:`);
    if (lean) out.push(`  ${displayVol}:`);
  }
  out.push("", "services:");
  if (lean) {
    out.push(
      "  display:",
      "    image: localhost/wadspaces-stream:trixie",
      `    container_name: wad-${spec.id}-display`,
    );
    const sideEnv = ["PUID", "PGID", "TZ"].filter((k) => k in spec.env).map((k) => `      - ${k}=${spec.env[k]}`);
    if (sideEnv.length) out.push("    environment:", ...sideEnv);
    out.push("    volumes:", `      - ${displayVol}:/run/wadspaces-display:z`);
    if (spec.devices.includes("/dev/dri")) out.push("    devices:", "      - /dev/dri:/dev/dri");
    out.push("    ports:", `      - 127.0.0.1:${spec.port}:3000`);
    if (spec.shmSize) out.push(`    shm_size: "${spec.shmSize}b"`);
    out.push('    restart: "no"', "");
  }
  out.push(
    `  ${spec.id}:`,
    `    image: ${spec.image}`,
    `    container_name: wad-${spec.id}`,
    "    labels:",
    `      wadspaces.id: ${spec.id}`,
  );
  if (env.length) out.push("    environment:", ...env);
  if (spec.secrets.length) out.push("    secrets:", ...spec.secrets.map((s) => `      - ${s}`));
  const svcVols = lean ? [...vols, `${displayVol}:/run/wadspaces-display:z`] : vols;
  // wadd mounts the projects' folders when it launches the wadspace; run by
  // hand, point these at folders of your own.
  const projects = (spec.projects ?? []).map((p) => `      # - /path/to/${p.mount}:/config/Desktop/${p.mount}:z  (project ${p.name})`);
  if (svcVols.length) out.push("    volumes:", ...svcVols.map((v) => `      - ${v}`), ...projects);
  else if (projects.length) out.push("    # volumes:", ...projects);
  if (spec.devices.length) out.push("    devices:", ...spec.devices.map((d) => `      - ${d}:${d}`));
  if (lean) out.push("    depends_on:", "      - display");
  else out.push("    ports:", `      - 127.0.0.1:${spec.port}:3000`);
  if (spec.shmSize) out.push(`    shm_size: "${spec.shmSize}b"`);
  out.push('    restart: "no"');
  return out.join("\n") + "\n";
}

// Where wadd keeps project folders and each workspace's projects.json
// (wadd/config.py DaemonConfig.projects_dir and state_dir).
export const PROJECTS_DIR = "/var/lib/wadspaces-projects";
export const STATE_DIR = "/var/lib/wadspaces";

/** Byte-identical to legacy/wadd-py/wadd/quadlet.py render_container_unit(). */
export function quadlet(w: WaddSpec, projectsDir = PROJECTS_DIR, stateDir = STATE_DIR): string {
  const native = w.display === "host";
  const lines = [
    "# Generated by `wadd gen-quadlets` from workspaces.yaml. Do not edit.",
    "[Unit]",
    `Description=WadSpaces workspace: ${w.name}`,
    "Wants=network-online.target",
    "After=network-online.target",
    "",
    "[Container]",
    `Image=${w.image}`,
    `ContainerName=${w.container_name || `wad-${w.id}`}`,
    `Label=wadspaces.id=${w.id}`,
  ];
  if (!native) lines.push(`PublishPort=127.0.0.1:${w.port}:${w.container_port ?? 3000}`);
  const env = w.env ?? {};
  for (const k of Object.keys(env).sort()) lines.push(`Environment=${k}=${env[k]}`);
  for (const s of w.secrets ?? []) lines.push(`Secret=${s}`);
  for (const v of w.volumes ?? []) lines.push(`Volume=${v}`);
  // Projects: each folder read-write on the Desktop, then the directory with
  // projects.json (a directory, so an atomic rewrite shows up inside). A
  // folder or drive project is the user's own path: never relabelled (no :z),
  // so the container runs without SELinux separation instead.
  const projects = w.projects ?? [];
  for (const p of projects) {
    lines.push(p.path ? `Volume=${p.path}:/config/Desktop/${p.mount}:rw` : `Volume=${projectsDir}/${p.id}:/config/Desktop/${p.mount}:rw,z`);
  }
  if (projects.length) lines.push(`Volume=${stateDir}/extra/${w.id}:/run/wadspaces-extra:ro,z`);
  // The kiosk session's sway (uid 1000) is the compositor it draws on.
  if (native) lines.push("Volume=/run/user/1000:/run/wadspaces-display");
  if (native || projects.some((p) => p.path)) lines.push("SecurityLabelDisable=true");
  for (const d of w.devices ?? []) lines.push(`AddDevice=${d}`);
  if (w.shm_size) lines.push(`ShmSize=${w.shm_size}`);
  lines.push(
    "Pull=missing",
    "",
    "[Service]",
    "Restart=no",
    "TimeoutStartSec=900",
    "",
    "# No [Install] section: wadd starts this unit on the first switch.",
    "",
  );
  return lines.join("\n");
}

function yamlScalar(v: unknown): string {
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  const s = String(v);
  return /^[A-Za-z0-9_./@-][A-Za-z0-9_./@:-]*$/.test(s) && !/^(true|false|null|yes|no|\d+)$/i.test(s)
    ? s
    : JSON.stringify(s);
}

export function workspacesYamlSnippet(w: WaddSpec): string {
  const out = [`  - id: ${w.id}`];
  for (const [k, v] of Object.entries(w)) {
    if (k === "id" || v == null) continue;
    if (Array.isArray(v)) {
      if (v.length) out.push(`    ${k}: [${v.map(yamlScalar).join(", ")}]`);
    } else if (typeof v === "object") {
      const entries = Object.entries(v as Record<string, string>);
      if (entries.length) {
        out.push(`    ${k}:`);
        for (const [ek, ev] of entries) out.push(`      ${ek}: ${JSON.stringify(ev)}`);
      }
    } else {
      out.push(`    ${k}: ${yamlScalar(v)}`);
    }
  }
  return out.join("\n") + "\n";
}

export function readme(spec: CreatorSpec): string {
  const features = resolveFeatures(spec);
  return `# ${spec.name}

Generated by Wad Creator.

| | |
|---|---|
| Features | ${features.join(", ") || "none"} |
| Default projects | ${(spec.projects ?? []).map((p) => p.name).join(", ") || "none"} |
| Web apps | ${spec.webapps.map((w) => w.name).join(", ") || "none"} |
| Kale Browser apps | ${spec.kaleResources.map((k) => k.app_name).join(", ") || "none"} |
| Display | ${displayOf(spec) === "host" ? "on the machine's screen (remote: stream sidecar)" : "streamed"} |
| Port | 127.0.0.1:${spec.port}${displayOf(spec) === "host" ? " (remote run only)" : ""} |
| Hotkey | ${spec.hotkey ? `Super+${spec.hotkey}` : "none"} |

## Build

Copy this folder to \`Wadspaces-David/${spec.id}/\`, then:

\`\`\`bash
cd Wadspaces-David
./build.sh --only ${spec.id}          # add --kalebrowser-local to use ../KaleBrowser
\`\`\`

## Run

On a WadSpaces machine, "Install on this machine" in Wad Creator adds it to
\`/etc/wadspaces/workspaces.yaml\`. By hand, add \`workspaces.yaml.snippet\` to
that file, or use \`wad-${spec.id}.container\` directly as a quadlet.

To try it without the switcher:

\`\`\`bash
${displayOf(spec) === "host"
  ? `../build.sh --only ${spec.id} --run          # streamed, as a remote host runs it
../build.sh --only ${spec.id} --run --local  # on this computer's own screen`
  : `podman-compose up -d && xdg-open http://127.0.0.1:${spec.port}`}
\`\`\`
${spec.secrets.length ? `\nSecrets it expects (create them with \`printf '%s' VALUE | podman secret create NAME -\`): ${spec.secrets.join(", ")}\n` : ""}`;
}

export interface BundleFile {
  path: string;
  content: string | Uint8Array;
}

/** The build folder. `dockerfileText` replaces the generated Dockerfile (a hand edit). */
export function bundleFiles(spec: CreatorSpec, wallpaper?: Uint8Array, dockerfileText?: string): BundleFile[] {
  const w = toWaddSpec(spec);
  const files: BundleFile[] = [
    { path: "Dockerfile", content: dockerfileText ?? dockerfile(spec) },
    { path: "docker-compose.yml", content: compose(spec) },
    { path: "README.md", content: readme(spec) },
    { path: `wad-${spec.id}.container`, content: quadlet(w) },
    { path: "workspaces.yaml.snippet", content: workspacesYamlSnippet(w) },
  ];
  if (spec.layout) files.push({ path: "root/etc/wadspaces/layout.json", content: layoutJson(spec) });
  if (spec.kaleResources.length) {
    files.push({ path: "root/etc/wadspaces/kalebrowser-resources.json", content: kaleResourcesJson(spec) });
  }
  if (spec.wallpaper && wallpaper) {
    files.push({ path: `root/usr/share/backgrounds/${spec.wallpaper.fileName}`, content: wallpaper });
  }
  return files;
}

export async function bundleZip(spec: CreatorSpec, wallpaper?: Uint8Array, dockerfileText?: string): Promise<Blob> {
  const { default: JSZip } = await import("jszip");
  const zip = new JSZip();
  const dir = zip.folder(spec.id)!;
  for (const f of bundleFiles(spec, wallpaper, dockerfileText)) dir.file(f.path, f.content);
  return zip.generateAsync({ type: "blob" });
}
