"""Configuration: /etc/wadspaces/workspaces.yaml.

The YAML file is the single source of truth for which workspaces exist, their
order, ports and hotkeys. Runtime state comes from podman.
"""
from __future__ import annotations

import os
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import yaml

ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}$")
BACKENDS = ("systemd", "podman")
SYSTEMD_SCOPES = ("system", "user")


class ConfigError(ValueError):
    pass


@dataclass
class WorkspaceSpec:
    id: str
    name: str
    image: str
    port: int
    hotkey: int | None = None
    icon: str | None = None
    enabled: bool = True
    container_name: str = ""
    container_port: int = 3000
    env: dict[str, str] = field(default_factory=dict)
    secrets: list[str] = field(default_factory=list)
    volumes: list[str] = field(default_factory=list)
    devices: list[str] = field(default_factory=list)
    shm_size: str | None = "1g"

    def __post_init__(self) -> None:
        if not self.container_name:
            self.container_name = f"wad-{self.id}"

    @property
    def url(self) -> str:
        return f"http://127.0.0.1:{self.port}/"

    @property
    def unit(self) -> str:
        """systemd unit generated by quadlet from wad-<id>.container."""
        return f"wad-{self.id}.service"


@dataclass
class HotkeyConfig:
    enabled: bool = True
    launcher: list[str] = field(default_factory=lambda: ["KEY_0", "KEY_SPACE"])


@dataclass
class DaemonConfig:
    bind: str = "127.0.0.1"
    port: int = 8080
    backend: str = "systemd"
    systemd_scope: str = "system"
    podman_socket: str = "/run/podman/podman.sock"
    cdp_url: str = "http://127.0.0.1:9222"
    hotkeys: HotkeyConfig = field(default_factory=HotkeyConfig)
    ready_timeout_s: int = 600
    # where CRUD writes wad-<id>.container units (systemd backend only)
    quadlet_dir: str = "/etc/containers/systemd"

    @property
    def base_url(self) -> str:
        host = "127.0.0.1" if self.bind in ("0.0.0.0", "::") else self.bind
        return f"http://{host}:{self.port}"


@dataclass
class LauncherConfig:
    wadcreator_url: str = "http://localhost:8081/"
    allow_navigate: list[str] = field(default_factory=list)


@dataclass
class WadCreatorConfig:
    """Wad Creator served locally by wadd from a built dist/ (temporary: it
    will move to wadcreator.com, talking to wadd through the cloud relay)."""
    enabled: bool = True
    bind: str = "127.0.0.1"
    port: int = 8081
    dist: str = "/usr/share/wadspaces/wadcreator"


@dataclass
class CloudConfig:
    project_id: str
    functions_region: str = "us-central1"
    api_key: str = ""
    state_file: str = "/var/lib/wadspaces/enrollment.json"
    functions_base: str = ""  # override, e.g. the emulator
    firestore_base: str = ""  # override, e.g. the emulator
    heartbeat_s: int = 30
    poll_s: int = 3

    @property
    def functions_url(self) -> str:
        return self.functions_base or f"https://{self.functions_region}-{self.project_id}.cloudfunctions.net"

    @property
    def firestore_url(self) -> str:
        base = self.firestore_base or "https://firestore.googleapis.com/v1"
        return f"{base}/projects/{self.project_id}/databases/(default)/documents"


@dataclass
class Config:
    machine_name: str
    daemon: DaemonConfig
    launcher: LauncherConfig
    cloud: CloudConfig | None
    workspaces: list[WorkspaceSpec]
    path: Path | None = None
    wadcreator: WadCreatorConfig = field(default_factory=WadCreatorConfig)

    def workspace(self, ws_id: str) -> WorkspaceSpec:
        for ws in self.workspaces:
            if ws.id == ws_id:
                return ws
        raise KeyError(ws_id)

    def by_hotkey(self, n: int) -> WorkspaceSpec | None:
        for ws in self.workspaces:
            if ws.enabled and ws.hotkey == n:
                return ws
        return None

    @property
    def enabled_workspaces(self) -> list[WorkspaceSpec]:
        return [ws for ws in self.workspaces if ws.enabled]


def _pick(data: dict, cls, name: str) -> dict:
    """Keep only keys the dataclass knows; unknown keys are a config error."""
    known = set(cls.__dataclass_fields__)
    unknown = set(data) - known
    if unknown:
        raise ConfigError(f"{name}: unknown keys {sorted(unknown)}")
    return data


def parse_config(data: dict[str, Any], path: Path | None = None) -> Config:
    if not isinstance(data, dict):
        raise ConfigError("config must be a mapping")
    version = data.get("version", 1)
    if version != 1:
        raise ConfigError(f"unsupported config version {version}")

    machine = data.get("machine") or {}
    machine_name = str(machine.get("name") or "wadspaces")

    d = dict(data.get("daemon") or {})
    hk = HotkeyConfig(**_pick(dict(d.pop("hotkeys", None) or {}), HotkeyConfig, "daemon.hotkeys"))
    daemon = DaemonConfig(hotkeys=hk, **_pick(d, DaemonConfig, "daemon"))
    if daemon.backend not in BACKENDS:
        raise ConfigError(f"daemon.backend must be one of {BACKENDS}")
    if daemon.systemd_scope not in SYSTEMD_SCOPES:
        raise ConfigError(f"daemon.systemd_scope must be one of {SYSTEMD_SCOPES}")

    launcher = LauncherConfig(**_pick(dict(data.get("launcher") or {}), LauncherConfig, "launcher"))

    wadcreator = WadCreatorConfig(**_pick(dict(data.get("wadcreator") or {}), WadCreatorConfig, "wadcreator"))

    cloud = None
    if data.get("cloud"):
        c = _pick(dict(data["cloud"]), CloudConfig, "cloud")
        if not c.get("project_id"):
            raise ConfigError("cloud.project_id is required when cloud is set")
        cloud = CloudConfig(**c)

    workspaces: list[WorkspaceSpec] = []
    seen_ids, seen_ports, seen_hotkeys, seen_names = set(), set(), set(), set()
    for i, raw in enumerate(data.get("workspaces") or []):
        where = f"workspaces[{i}]"
        raw = dict(_pick(dict(raw), WorkspaceSpec, where))
        for req in ("id", "name", "image", "port"):
            if req not in raw:
                raise ConfigError(f"{where}: missing {req}")
        raw["env"] = {str(k): str(v) for k, v in (raw.get("env") or {}).items()}
        ws = WorkspaceSpec(**raw)
        where = f"workspace {ws.id!r}"
        if not ID_RE.match(ws.id):
            raise ConfigError(f"{where}: id must match {ID_RE.pattern}")
        if ws.id in seen_ids:
            raise ConfigError(f"{where}: duplicate id")
        if not (1 <= int(ws.port) <= 65535):
            raise ConfigError(f"{where}: port out of range")
        if ws.port in seen_ports or ws.port == daemon.port or (wadcreator.enabled and ws.port == wadcreator.port):
            raise ConfigError(f"{where}: port {ws.port} already used")
        if ws.container_name in seen_names:
            raise ConfigError(f"{where}: duplicate container_name")
        if ws.hotkey is not None:
            if not (1 <= int(ws.hotkey) <= 9):
                raise ConfigError(f"{where}: hotkey must be 1..9")
            if ws.enabled and ws.hotkey in seen_hotkeys:
                raise ConfigError(f"{where}: hotkey {ws.hotkey} already used")
            if ws.enabled:
                seen_hotkeys.add(ws.hotkey)
        seen_ids.add(ws.id)
        seen_ports.add(ws.port)
        seen_names.add(ws.container_name)
        workspaces.append(ws)

    return Config(machine_name=machine_name, daemon=daemon, launcher=launcher,
                  cloud=cloud, workspaces=workspaces, path=path, wadcreator=wadcreator)


def workspace_to_dict(ws: WorkspaceSpec) -> dict:
    d = asdict(ws)
    if d["container_name"] == f"wad-{ws.id}":
        del d["container_name"]
    if d["container_port"] == 3000:
        del d["container_port"]
    return {k: v for k, v in d.items() if v not in (None, [], {})}


def config_to_dict(cfg: Config) -> dict:
    out: dict[str, Any] = {
        "version": 1,
        "machine": {"name": cfg.machine_name},
        "daemon": asdict(cfg.daemon),
        "launcher": asdict(cfg.launcher),
        "wadcreator": asdict(cfg.wadcreator),
    }
    if cfg.cloud:
        out["cloud"] = asdict(cfg.cloud)
    out["workspaces"] = [workspace_to_dict(ws) for ws in cfg.workspaces]
    return out


def save_config(cfg: Config, path: str | Path | None = None) -> Path:
    """Atomically rewrite the YAML (comments are not preserved)."""
    path = Path(path or cfg.path)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text("# Managed by wadd; edits through Wad Creator rewrite this file.\n"
                   + yaml.safe_dump(config_to_dict(cfg), sort_keys=False), encoding="utf-8")
    os.replace(tmp, path)
    return path


def load_config(path: str | Path) -> Config:
    path = Path(path)
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except FileNotFoundError as e:
        raise ConfigError(f"config not found: {path}") from e
    except yaml.YAMLError as e:
        raise ConfigError(f"{path}: {e}") from e
    return parse_config(data or {}, path)
