"""Render podman quadlet .container units from workspaces.yaml.

Wad Creator's src/templates/quadlet.ts must produce byte-identical output for
the same workspace; tests/fixtures/wad-writing.container is shared by both
test suites.
"""
from __future__ import annotations

from pathlib import Path

from .config import Config, WorkspaceSpec

HEADER = "# Generated by `wadd gen-quadlets` from workspaces.yaml. Do not edit.\n"


def render_container_unit(ws: WorkspaceSpec) -> str:
    lines = [
        HEADER.rstrip("\n"),
        "[Unit]",
        f"Description=WadSpaces workspace: {ws.name}",
        "Wants=network-online.target",
        "After=network-online.target",
        "",
        "[Container]",
        f"Image={ws.image}",
        f"ContainerName={ws.container_name}",
        f"Label=wadspaces.id={ws.id}",
        f"PublishPort=127.0.0.1:{ws.port}:{ws.container_port}",
    ]
    for k, v in sorted(ws.env.items()):
        lines.append(f"Environment={k}={v}")
    for s in ws.secrets:
        lines.append(f"Secret={s}")
    for v in ws.volumes:
        lines.append(f"Volume={v}")
    for d in ws.devices:
        lines.append(f"AddDevice={d}")
    if ws.shm_size:
        lines.append(f"ShmSize={ws.shm_size}")
    lines += [
        "Pull=missing",
        "",
        "[Service]",
        "Restart=no",
        "TimeoutStartSec=900",
        "",
        "# No [Install] section: wadd starts this unit on the first switch.",
        "",
    ]
    return "\n".join(lines)


def unit_filename(ws: WorkspaceSpec) -> str:
    return f"wad-{ws.id}.container"


def gen_quadlets(cfg: Config, out_dir: str | Path, prune: bool = True) -> list[Path]:
    """Write one .container per workspace; remove stale wad-*.container files."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    wanted = set()
    for ws in cfg.workspaces:
        p = out / unit_filename(ws)
        p.write_text(render_container_unit(ws), encoding="utf-8")
        written.append(p)
        wanted.add(p.name)
    if prune:
        for p in out.glob("wad-*.container"):
            if p.name not in wanted:
                p.unlink()
    return written
