"""Render podman quadlet .container units from workspaces.yaml.

Wad Creator's src/core/generator (quadlet) must produce byte-identical output
for the same workspace; the tests/fixtures/wad-writing*.container files are
shared by both test suites.
"""
from __future__ import annotations

from pathlib import Path

from .config import Config, DaemonConfig, WorkspaceSpec

# A native (display: host) workspace is a lean image (containers/_common) that
# draws on the kiosk session's sway: sway's runtime dir is mounted where the
# image looks for a compositor, and it uses the one wayland-N socket there
# (set WADSPACES_WAYLAND in env to pin a name). The kiosk user is
# pinned to uid 1000 (host sysusers.d) so the container's abc user (PUID 1000)
# owns the socket too. SELinux would stop a container_t process connecting to
# a user socket, hence no label.
HOST_RUNTIME_DIR = "/run/user/1000"
DISPLAY_MOUNT = "/run/wadspaces-display"

# A workspace's projects (wadd/projects.py) are host folders mounted
# read-write on its Desktop, and the list of them (projects.json, for the
# image's wadspaces-projects) comes in a directory of its own: a directory, not
# the file, so rewriting the file atomically shows up inside. Only images
# labelled io.wadspaces.projects=1 get these (wadd/launches.py checks).
# A folder or drive project (one with a path) is mounted from that path,
# without :z: relabelling someone's home folder or a whole drive for
# containers would be harmful. The container runs unlabelled instead
# (SecurityLabelDisable, as a native workspace does).
PROJECTS_DIR = DaemonConfig.projects_dir
STATE_DIR = DaemonConfig.state_dir
EXTRA_MOUNT = "/run/wadspaces-extra"

# Rootless podman (wadd under the user's systemd, e.g. on a laptop): the
# container's root is the host user and its uid 1000 some subordinate id, so
# abc (PUID 1000) couldn't write the host user's project folders. These maps
# put the host user at uid 1000 inside instead and keep the rest of the
# default 65536-id range. keep-id would too, but it also adds a passwd entry
# for that uid, which stops the image's init moving abc onto it.
SUBORDINATE_IDS = 65536


def _id_maps(uid: int) -> list[str]:
    ranges = [f"0:1:{uid}", f"{uid}:0:1", f"{uid + 1}:{uid + 1}:{SUBORDINATE_IDS - uid - 1}"]
    return [f"UIDMap={r}" for r in ranges] + [f"GIDMap={r}" for r in ranges]


HEADER = "# Generated by `wadd gen-quadlets` from workspaces.yaml. Do not edit.\n"


def render_container_unit(ws: WorkspaceSpec, projects_dir: str = PROJECTS_DIR,
                          state_dir: str = STATE_DIR, rootless_uid: int | None = None) -> str:
    lines = [
        HEADER.rstrip("\n"),
        "[Unit]",
        f"Description=WadSpaces workspace: {ws.name}",
        "Wants=network-online.target",
        "After=network-online.target",
        "",
        "[Container]",
        f"Image={ws.image}",
        f"ContainerName={ws.container_name}",
        f"Label=wadspaces.id={ws.id}",
    ]
    if rootless_uid is not None:
        lines += _id_maps(rootless_uid)
    if not ws.native:
        lines.append(f"PublishPort=127.0.0.1:{ws.port}:{ws.container_port}")
    for k, v in sorted(ws.env.items()):
        lines.append(f"Environment={k}={v}")
    for s in ws.secrets:
        lines.append(f"Secret={s}")
    for v in ws.volumes:
        lines.append(f"Volume={v}")
    for p in ws.projects:
        if p.get("path"):
            lines.append(f"Volume={p['path']}:/config/Desktop/{p['mount']}:rw")
        else:
            lines.append(f"Volume={projects_dir}/{p['id']}:/config/Desktop/{p['mount']}:rw,z")
    if ws.projects:
        lines.append(f"Volume={state_dir}/extra/{ws.id}:{EXTRA_MOUNT}:ro,z")
    if ws.native:
        lines.append(f"Volume={HOST_RUNTIME_DIR}:{DISPLAY_MOUNT}")
    if ws.native or any(p.get("path") for p in ws.projects):
        lines.append("SecurityLabelDisable=true")
    for d in ws.devices:
        lines.append(f"AddDevice={d}")
    if ws.shm_size:
        lines.append(f"ShmSize={ws.shm_size}")
    lines += [
        "Pull=missing",
        "",
        "[Service]",
        "Restart=no",
        "TimeoutStartSec=900",
        "",
        "# No [Install] section: wadd starts this unit on the first switch.",
        "",
    ]
    return "\n".join(lines)


def _render(cfg: Config, ws: WorkspaceSpec) -> str:
    d = cfg.daemon
    rootless = d.projects_uid if d.backend == "systemd" and d.systemd_scope == "user" else None
    return render_container_unit(ws, d.projects_dir, d.state_dir, rootless)


def unit_filename(ws: WorkspaceSpec) -> str:
    return f"wad-{ws.id}.container"


def quadlets_current(cfg: Config, out_dir: str | Path) -> bool:
    """Whether the units on disk are exactly what this wadd would write."""
    out = Path(out_dir)
    wanted = {unit_filename(ws): _render(cfg, ws) for ws in cfg.workspaces}
    have = {p.name for p in out.glob("wad-*.container")} if out.is_dir() else set()
    if have != set(wanted):
        return False
    return all((out / name).read_text(encoding="utf-8") == text for name, text in wanted.items())


def gen_quadlets(cfg: Config, out_dir: str | Path, prune: bool = True) -> list[Path]:
    """Write one .container per workspace; remove stale wad-*.container files."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    wanted = set()
    for ws in cfg.workspaces:
        p = out / unit_filename(ws)
        p.write_text(_render(cfg, ws), encoding="utf-8")
        written.append(p)
        wanted.add(p.name)
    if prune:
        for p in out.glob("wad-*.container"):
            if p.name not in wanted:
                p.unlink()
    return written
