//! Wad Creator on a machine: the React UI (`apps/wadcreator/src`) in a Tauri
//! window, running as the kiosk user. The UI calls into Rust through typed
//! commands (generated into `src/gen/bindings.ts`); Rust talks to wadd, GitHub
//! and Firestore, so values like the GitHub token never reach JavaScript.

mod github;
mod rswadd;
#[cfg(feature = "spike")]
mod spike;
mod theme;
mod wadd;
mod window;

use specta_typescript::Typescript;
use tauri::Manager;
use tauri_specta::{ErrorHandlingMode, collect_commands};

/// Where the UI's generated bindings live, relative to this crate.
const BINDINGS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../src/gen/bindings.ts");

const USAGE: &str = "usage: wadcreator [--kiosk | --version | --export-bindings]";

/// The app's version, for Settings and support.
#[tauri::command]
#[specta::specta]
fn app_version() -> String {
    env!("CARGO_PKG_VERSION").into()
}

fn commands() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .commands(collect_commands![
            app_version,
            github::github_device_start,
            github::github_device_wait,
            github::github_device_cancel,
            github::github_open_browser,
            theme::set_theme,
            wadd::wadd_request,
            wadd::wadd_last_state,
            wadd::wadd_kind,
        ])
        .events(tauri_specta::collect_events![wadd::WaddEvent])
}

fn export_bindings(path: &std::path::Path) -> Result<(), String> {
    let ts = Typescript::default()
        .header("// Generated by `cargo xtask bindings` from apps/wadcreator/src-tauri. Don't edit.");
    commands().export(ts, path).map_err(|e| e.to_string())
}

fn run(kiosk: bool) {
    let commands = commands();
    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            // A second launch (the session restarting us, a stray click)
            // brings the running app forward instead.
            if let Some(w) = app.get_webview_window(window::MAIN) {
                let _ = w.set_focus();
            }
        }))
        .manage(github::GithubState::new())
        .manage(wadd::Wadd::new())
        .invoke_handler({
            // Commands with a raw body aren't in the bindings; the rest are.
            let typed = commands.invoke_handler();
            let raw: fn(tauri::ipc::Invoke<tauri::Wry>) -> bool = tauri::generate_handler![wadd::wadd_build_context];
            move |invoke| match invoke.message.command() {
                // Only the app's own window: never a web page (the GitHub window).
                _ if invoke.message.webview_ref().label() != window::MAIN => {
                    tracing::warn!(window = invoke.message.webview_ref().label(), "refused a command");
                    invoke.resolver.reject("not allowed");
                    true
                }
                "wadd_build_context" => raw(invoke),
                _ => typed(invoke),
            }
        })
        .setup(move |app| {
            commands.mount_events(app);
            wadd::follow_events(app.handle().clone());
            let _main = window::open_main(app.handle(), kiosk)?;
            #[cfg(feature = "spike")]
            spike::start(app.handle().clone(), _main);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("Wad Creator failed to start");
}

pub fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "wadcreator=info,warn".into()),
        )
        .init();
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.iter().map(String::as_str).collect::<Vec<_>>()[..] {
        [] => run(false),
        ["--kiosk"] => run(true),
        ["--version"] => println!("wadcreator {}", env!("CARGO_PKG_VERSION")),
        ["--export-bindings"] => {
            if let Err(e) = export_bindings(BINDINGS.as_ref()) {
                eprintln!("wadcreator: {e}");
                std::process::exit(1);
            }
            eprintln!("wrote {BINDINGS}");
        }
        _ => {
            eprintln!("{USAGE}");
            std::process::exit(2);
        }
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn bindings_are_current() {
        let dir = std::env::temp_dir().join(format!("wadcreator-bindings-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let fresh = dir.join("bindings.ts");
        super::export_bindings(&fresh).unwrap();
        let fresh = std::fs::read_to_string(&fresh).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
        let committed = std::fs::read_to_string(super::BINDINGS).unwrap_or_default();
        assert!(fresh == committed, "src/gen/bindings.ts is out of date: run `cargo xtask bindings`");
    }
}
