//! The files of a workspace's build folder (src/core/generator/index.ts), the
//! same shape as the hand-written Wadspaces-David/<dir>/ directories:
//!
//!   Dockerfile  docker-compose.yml  README.md  wad-<id>.container  workspaces.yaml.snippet
//!   root/etc/wadspaces/layout.json                  (Builder desktops: icons in order)
//!   root/etc/wadspaces/kalebrowser-resources.json   (Kale Browser apps only)
//!   root/usr/share/backgrounds/wallpaper.<ext>      (when a wallpaper is set)
//!
//! Project files are never in it: wadd mounts them when it launches.

use serde_json::Value;

use crate::build::layout_json;
use crate::js;
use crate::spec::{display_of, resolve_features, to_wadd_spec, volumes_for};

/// A shell-safe double-quoted string (Dockerfile ENV and RUN arguments).
fn q(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        if matches!(c, '"' | '\\' | '$' | '`') {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('"');
    out
}

pub fn dockerfile(spec: &Value) -> String {
    let features = resolve_features(spec);
    let kale = !js::arr(spec, "kaleResources").is_empty();
    let name = js::field(spec, "name");
    let mut lines: Vec<String> = vec![
        format!("# {name} workspace. Generated by Wad Creator."),
        format!("ARG BASE_IMAGE={}", js::field(spec, "baseImage")),
        "FROM ${BASE_IMAGE}".into(),
        String::new(),
    ];
    if kale {
        lines.push("ARG KALEBROWSER_REF=main".into());
    }
    let mut env = vec![format!("TITLE={}", q(&name))];
    if let Some(w) = spec.get("wallpaper").filter(|w| js::truthy(w)) {
        env.push(format!("WALLPAPER={}", q(&format!("/usr/share/backgrounds/{}", js::field(w, "fileName")))));
        let mode = js::field(w, "mode");
        if mode != "center" {
            env.push(format!("WALLPAPER_MODE={mode}"));
        }
        let color = js::field(w, "color");
        if color != "#0b0b14" {
            env.push(format!("WALLPAPER_COLOR={}", q(&color)));
        }
    }
    lines.push(format!("ENV {}", env.join(" \\\n    ")));
    lines.push(String::new());
    if !features.is_empty() {
        lines.push(format!("RUN wadspaces-feature {}", features.join(" ")));
        lines.push(String::new());
    }
    let apt = js::arr(spec, "aptApps");
    if !apt.is_empty() {
        // One RUN: apt's lists are fetched once, and --clean drops them from the layer.
        let mut cmds: Vec<String> = apt
            .iter()
            .map(|a| {
                let mut parts = vec!["wadspaces-apt".to_string(), js::field(a, "id")];
                if let Some(d) = a.get("desktop").filter(|d| js::truthy(d)) {
                    parts.push("--desktop".into());
                    parts.push(js::string(d));
                }
                parts.extend(js::strs(a, "packages"));
                parts.join(" ")
            })
            .collect();
        cmds.push("wadspaces-apt --clean".into());
        lines.push(format!("RUN {}", cmds.join(" && \\\n    ")));
        lines.push(String::new());
    }
    let webapps = js::arr(spec, "webapps");
    if !webapps.is_empty() {
        let cmds: Vec<String> = webapps
            .iter()
            .map(|w| {
                let id = match w.get("id").filter(|i| js::truthy(i)) {
                    Some(i) => format!("--id {} ", js::string(i)),
                    None => String::new(),
                };
                format!("wadspaces-webapp {id}{} {}", q(&js::field(w, "name")), js::field(w, "url"))
            })
            .collect();
        lines.push(format!("RUN {}", cmds.join(" && \\\n    ")));
        lines.push(String::new());
    }
    lines.push("COPY root/ /".into());
    if kale {
        lines.push(String::new());
        lines.push("RUN wadspaces-kalebrowser-install --ref \"${KALEBROWSER_REF}\" \\".into());
        lines.push("      --resources /etc/wadspaces/kalebrowser-resources.json".into());
    }
    lines.join("\n") + "\n"
}

pub fn kale_resources_json(spec: &Value) -> String {
    match spec.get("kaleResources") {
        Some(k) => js::stringify_pretty(k, 4) + "\n",
        None => "undefined\n".into(),
    }
}

/// docker-compose.yml, for running it by hand. A native (display: host)
/// workspace runs remotely as two containers, the workspace and the stream
/// sidecar it draws on; a streamed one is a single Selkies container.
pub fn compose(spec: &Value) -> String {
    let id = js::field(spec, "id");
    let name = js::field(spec, "name");
    let port = js::field(spec, "port");
    let env_obj = spec.get("env").and_then(Value::as_object).cloned().unwrap_or_default();
    let env: Vec<String> = env_obj.iter().map(|(k, v)| format!("      - {k}={}", js::string(v))).collect();
    let lean = display_of(spec) == "host";
    let display_vol = format!("{id}-display");
    let vols = volumes_for(spec);
    let secrets = js::strs(spec, "secrets");
    let devices = js::strs(spec, "devices");
    let shm = spec.get("shmSize").filter(|s| js::truthy(s)).map(js::string);
    let mut out: Vec<String> = if lean {
        vec![
            "---".into(),
            format!("# {name} workspace, run remotely: the workspace plus the stream"),
            "# sidecar that shows it in a browser. Generated by Wad Creator. On a".into(),
            "# WadSpaces machine wadd runs the same image on the screen instead.".into(),
            format!("#   ../build.sh --only {id} --run"),
            format!("# then open http://127.0.0.1:{port}"),
        ]
    } else {
        vec![
            "---".into(),
            format!("# {name} workspace. Generated by Wad Creator. Normally started by wadd;"),
            "# this file is for building and running it by hand:".into(),
            format!("#   ../build.sh --only {id} && podman-compose up -d"),
            format!("# then open http://127.0.0.1:{port}"),
        ]
    };
    if !secrets.is_empty() {
        out.push("secrets:".into());
        for s in &secrets {
            out.push(format!("  {s}:"));
            out.push("    external: true".into());
        }
    }
    if !vols.is_empty() || lean {
        out.push(String::new());
        out.push("volumes:".into());
        for v in &vols {
            out.push(format!("  {}:", v.split(':').next().unwrap_or("")));
        }
        if lean {
            out.push(format!("  {display_vol}:"));
        }
    }
    out.push(String::new());
    out.push("services:".into());
    if lean {
        out.push("  display:".into());
        out.push("    image: localhost/wadspaces-stream:trixie".into());
        out.push(format!("    container_name: wad-{id}-display"));
        let side_env: Vec<String> = ["PUID", "PGID", "TZ"]
            .iter()
            .filter_map(|k| env_obj.get(*k).map(|v| format!("      - {k}={}", js::string(v))))
            .collect();
        if !side_env.is_empty() {
            out.push("    environment:".into());
            out.extend(side_env);
        }
        out.push("    volumes:".into());
        out.push(format!("      - {display_vol}:/run/wadspaces-display:z"));
        if devices.iter().any(|d| d == "/dev/dri") {
            out.push("    devices:".into());
            out.push("      - /dev/dri:/dev/dri".into());
        }
        out.push("    ports:".into());
        out.push(format!("      - 127.0.0.1:{port}:3000"));
        if let Some(s) = &shm {
            out.push(format!("    shm_size: \"{s}b\""));
        }
        out.push("    restart: \"no\"".into());
        out.push(String::new());
    }
    out.push(format!("  {id}:"));
    out.push(format!("    image: {}", js::field(spec, "image")));
    out.push(format!("    container_name: wad-{id}"));
    out.push("    labels:".into());
    out.push(format!("      wadspaces.id: {id}"));
    if !env.is_empty() {
        out.push("    environment:".into());
        out.extend(env);
    }
    if !secrets.is_empty() {
        out.push("    secrets:".into());
        out.extend(secrets.iter().map(|s| format!("      - {s}")));
    }
    let mut svc_vols = vols.clone();
    if lean {
        svc_vols.push(format!("{display_vol}:/run/wadspaces-display:z"));
    }
    // wadd mounts the projects' folders when it launches the wadspace; run by
    // hand, point these at folders of your own.
    let projects: Vec<String> = js::arr(spec, "projects")
        .iter()
        .map(|p| {
            let mount = js::field(p, "mount");
            format!("      # - /path/to/{mount}:/config/Desktop/{mount}:z  (project {})", js::field(p, "name"))
        })
        .collect();
    if !svc_vols.is_empty() {
        out.push("    volumes:".into());
        out.extend(svc_vols.iter().map(|v| format!("      - {v}")));
        out.extend(projects);
    } else if !projects.is_empty() {
        out.push("    # volumes:".into());
        out.extend(projects);
    }
    if !devices.is_empty() {
        out.push("    devices:".into());
        out.extend(devices.iter().map(|d| format!("      - {d}:{d}")));
    }
    if lean {
        out.push("    depends_on:".into());
        out.push("      - display".into());
    } else {
        out.push("    ports:".into());
        out.push(format!("      - 127.0.0.1:{port}:3000"));
    }
    if let Some(s) = &shm {
        out.push(format!("    shm_size: \"{s}b\""));
    }
    out.push("    restart: \"no\"".into());
    out.join("\n") + "\n"
}

/// Where wadd keeps project folders and each workspace's projects.json.
pub const PROJECTS_DIR: &str = "/var/lib/wadspaces-projects";
pub const STATE_DIR: &str = "/var/lib/wadspaces";

/// Rootless podman (wadd under your own systemd, on a laptop): the
/// container's root is you and its uid 1000 a subordinate id, so abc (PUID
/// 1000) couldn't write your project folders. These maps put you at uid 1000
/// inside instead and keep the rest of the usual 65536 ids. (keep-id would
/// too, but its passwd entry stops the image's init moving abc onto that uid.)
const SUBORDINATE_IDS: u32 = 65536;

fn id_maps(uid: u32) -> Vec<String> {
    let ranges =
        [format!("0:1:{uid}"), format!("{uid}:0:1"), format!("{}:{}:{}", uid + 1, uid + 1, SUBORDINATE_IDS - uid - 1)];
    ranges.iter().map(|r| format!("UIDMap={r}")).chain(ranges.iter().map(|r| format!("GIDMap={r}"))).collect()
}

/// wadd's quadlet unit for a workspace (wad-<id>.container). `rootless_uid`:
/// the host user to map to uid 1000 inside (rootless podman only).
pub fn quadlet(w: &Value, projects_dir: &str, state_dir: &str, rootless_uid: Option<u32>) -> String {
    workspace_unit(w, projects_dir, state_dir, rootless_uid, None)
}

/// The workspace's unit. `sidecar`: a native workspace draws on its stream
/// sidecar's display volume (stream_quadlets) instead of the machine's screen.
fn workspace_unit(
    w: &Value,
    projects_dir: &str,
    state_dir: &str,
    rootless_uid: Option<u32>,
    sidecar: Option<&str>,
) -> String {
    let native = w.get("display").and_then(Value::as_str) == Some("host");
    let id = js::field(w, "id");
    let container_name = match w.get("container_name").filter(|c| js::truthy(c)) {
        Some(c) => js::string(c),
        None => format!("wad-{id}"),
    };
    let mut lines: Vec<String> = vec![
        "# Generated by `wadd gen-quadlets` from workspaces.yaml. Do not edit.".into(),
        "[Unit]".into(),
        format!("Description=WadSpaces workspace: {}", js::field(w, "name")),
        "Wants=network-online.target".into(),
        "After=network-online.target".into(),
    ];
    if let Some(display) = sidecar {
        lines.push(format!("Requires={display}.service"));
        lines.push(format!("After={display}.service"));
    }
    lines.extend([
        String::new(),
        "[Container]".into(),
        format!("Image={}", js::field(w, "image")),
        format!("ContainerName={container_name}"),
        format!("Label=wadspaces.id={id}"),
    ]);
    if let Some(uid) = rootless_uid {
        lines.extend(id_maps(uid));
    }
    if !native {
        let cport = js::present(w, "container_port").map(js::string).unwrap_or_else(|| "3000".into());
        lines.push(format!("PublishPort=127.0.0.1:{}:{cport}", js::field(w, "port")));
    }
    let env = w.get("env").and_then(Value::as_object).cloned().unwrap_or_default();
    let mut keys: Vec<&String> = env.keys().collect();
    keys.sort_by(|a, b| js::cmp16(a, b));
    for k in keys {
        lines.push(format!("Environment={k}={}", js::string(&env[k.as_str()])));
    }
    for s in js::strs(w, "secrets") {
        lines.push(format!("Secret={s}"));
    }
    for v in js::strs(w, "volumes") {
        lines.push(format!("Volume={v}"));
    }
    // Projects: each folder read-write on the Desktop, then the directory with
    // projects.json. A folder or drive project is the user's own path: never
    // relabelled (no :z), so the container runs without SELinux separation.
    let projects = js::arr(w, "projects");
    for p in projects {
        let mount = js::field(p, "mount");
        match p.get("path").filter(|x| js::truthy(x)) {
            Some(path) => lines.push(format!("Volume={}:/config/Desktop/{mount}:rw", js::string(path))),
            None => lines.push(format!("Volume={projects_dir}/{}:/config/Desktop/{mount}:rw,z", js::field(p, "id"))),
        }
    }
    if !projects.is_empty() {
        lines.push(format!("Volume={state_dir}/extra/{id}:/run/wadspaces-extra:ro,z"));
    }
    // The kiosk session's sway (uid 1000) is the compositor it draws on, or
    // its stream sidecar's.
    match sidecar {
        Some(display) => lines.push(format!("Volume={display}.volume:/run/wadspaces-display:z")),
        None if native => lines.push("Volume=/run/user/1000:/run/wadspaces-display".into()),
        None => {}
    }
    if (native && sidecar.is_none()) || projects.iter().any(|p| p.get("path").is_some_and(js::truthy)) {
        lines.push("SecurityLabelDisable=true".into());
    }
    for d in js::strs(w, "devices") {
        lines.push(format!("AddDevice={d}"));
    }
    if let Some(s) = w.get("shm_size").filter(|s| js::truthy(s)) {
        lines.push(format!("ShmSize={}", js::string(s)));
    }
    for l in [
        "Pull=missing",
        "",
        "[Service]",
        "Restart=no",
        "TimeoutStartSec=900",
        "",
        "# No [Install] section: wadd starts this unit on the first switch.",
        "",
    ] {
        lines.push(l.into());
    }
    lines.join("\n")
}

/// A YAML scalar as wadd's file has them: bare when that's unambiguous.
fn yaml_scalar(v: &Value) -> String {
    if v.is_number() || v.is_boolean() {
        return js::string(v);
    }
    let s = js::string(v);
    let plain = {
        let mut cs = s.chars();
        let first = |c: char| c.is_ascii_alphanumeric() || matches!(c, '_' | '.' | '/' | '@' | '-');
        matches!(cs.next(), Some(c) if first(c)) && cs.all(|c| first(c) || c == ':')
    };
    let keyword = {
        let l = s.to_ascii_lowercase();
        matches!(l.as_str(), "true" | "false" | "null" | "yes" | "no")
            || (!s.is_empty() && s.chars().all(|c| c.is_ascii_digit()))
    };
    if plain && !keyword { s } else { js::stringify(&Value::String(s)) }
}

/// A native workspace, streamed: its unit (drawing on the sidecar's display
/// instead of the machine's screen), the sidecar (`_stream`: Selkies, its
/// compositor and web client), and the display volume they share. `stream`:
/// { port (published on every address), user, image, tls_dir (cert.pem,
/// key.pem) }. The password is podman secret `wad_stream_password`: nginx in
/// the sidecar asks for it on every path (pages and the websocket), over
/// TLS only (the plain-HTTP port isn't published). (file name, text) each.
pub fn stream_quadlets(
    w: &Value,
    stream: &Value,
    projects_dir: &str,
    state_dir: &str,
    rootless_uid: Option<u32>,
) -> Vec<(String, String)> {
    let id = js::field(w, "id");
    let display = format!("wad-{id}-display");
    let workspace = workspace_unit(w, projects_dir, state_dir, rootless_uid, Some(&display));
    let env = w.get("env").and_then(Value::as_object).cloned().unwrap_or_default();
    let tls = js::field(stream, "tls_dir");
    let mut lines: Vec<String> = vec![
        "# Generated by wadd: the stream a workspace draws on when it's viewed from".into(),
        "# another device. Do not edit.".into(),
        "[Unit]".into(),
        format!("Description=WadSpaces stream: {}", js::field(w, "name")),
        String::new(),
        "[Container]".into(),
        format!("Image={}", js::field(stream, "image")),
        format!("ContainerName={display}"),
        format!("Label=wadspaces.id={id}"),
        "Label=wadspaces.role=display".into(),
    ];
    if let Some(uid) = rootless_uid {
        lines.extend(id_maps(uid));
    }
    lines.push(format!("Environment=CUSTOM_USER={}", js::field(stream, "user")));
    for k in ["PGID", "PUID", "TZ"] {
        if let Some(v) = env.get(k) {
            lines.push(format!("Environment={k}={}", js::string(v)));
        }
    }
    // No file transfers: they'd land in the sidecar, not the workspace.
    lines.push("Environment=SELKIES_FILE_TRANSFERS=none".into());
    lines.push(format!("Environment=TITLE={}", js::field(w, "name")));
    lines.push("Secret=wad_stream_password,type=env,target=PASSWORD".into());
    lines.push(format!("Volume={display}.volume:/run/wadspaces-display:z"));
    lines.push(format!("Volume={tls}/cert.pem:/config/ssl/cert.pem:ro,z"));
    lines.push(format!("Volume={tls}/key.pem:/config/ssl/cert.key:ro,z"));
    lines.push(format!("PublishPort={}:3001", js::field(stream, "port")));
    if js::strs(w, "devices").iter().any(|d| d == "/dev/dri") {
        lines.push("AddDevice=/dev/dri".into());
    }
    if let Some(s) = w.get("shm_size").filter(|s| js::truthy(s)) {
        lines.push(format!("ShmSize={}", js::string(s)));
    }
    // 900 s as a workspace: rootless podman copies a whole image the first
    // time it maps its uids (minutes for this one).
    for l in ["Pull=never", "", "[Service]", "Restart=no", "TimeoutStartSec=900", ""] {
        lines.push(l.into());
    }
    // Owned by abc (1000): a plain volume is root's each time it's mounted,
    // which locked the sidecar out of its own socket.
    let volume = [
        "# Generated by wadd: the display a streamed workspace and its sidecar share.",
        "[Volume]",
        &format!("VolumeName={display}"),
        "User=1000",
        "Group=1000",
        "",
    ]
    .join("\n");
    vec![
        (format!("wad-{id}.container"), workspace),
        (format!("{display}.container"), lines.join("\n")),
        (format!("{display}.volume"), volume),
    ]
}

/// This workspace as an entry of /etc/wadspaces/workspaces.yaml.
pub fn workspaces_yaml_snippet(w: &Value) -> String {
    let mut out = vec![format!("  - id: {}", js::field(w, "id"))];
    for (k, v) in js::obj(w) {
        if k == "id" || v.is_null() {
            continue;
        }
        match &v {
            Value::Array(a) => {
                if !a.is_empty() {
                    out.push(format!("    {k}: [{}]", a.iter().map(yaml_scalar).collect::<Vec<_>>().join(", ")));
                }
            }
            Value::Object(o) => {
                if !o.is_empty() {
                    out.push(format!("    {k}:"));
                    for (ek, ev) in o {
                        out.push(format!("      {ek}: {}", js::stringify(ev)));
                    }
                }
            }
            _ => out.push(format!("    {k}: {}", yaml_scalar(&v))),
        }
    }
    out.join("\n") + "\n"
}

pub fn readme(spec: &Value) -> String {
    let features = resolve_features(spec);
    let host = display_of(spec) == "host";
    let id = js::field(spec, "id");
    let port = js::field(spec, "port");
    let or_none = |s: String| if s.is_empty() { "none".to_string() } else { s };
    let hotkey = match spec.get("hotkey").filter(|h| js::truthy(h)) {
        Some(h) => format!("Super+{}", js::string(h)),
        None => "none".into(),
    };
    let secrets = js::strs(spec, "secrets");
    let run = if host {
        format!(
            "../build.sh --only {id} --run          # streamed, as a remote host runs it\n../build.sh --only {id} --run --local  # on this computer's own screen"
        )
    } else {
        format!("podman-compose up -d && xdg-open http://127.0.0.1:{port}")
    };
    let secrets_note = if secrets.is_empty() {
        String::new()
    } else {
        format!(
            "\nSecrets it expects (create them with `printf '%s' VALUE | podman secret create NAME -`): {}\n",
            secrets.join(", ")
        )
    };
    format!(
        "# {name}\n\nGenerated by Wad Creator.\n\n| | |\n|---|---|\n| Features | {features} |\n| Default projects | {projects} |\n| Web apps | {webapps} |\n| Kale Browser apps | {kale} |\n| Display | {display} |\n| Port | 127.0.0.1:{port}{remote} |\n| Hotkey | {hotkey} |\n\n## Build\n\nCopy this folder to `Wadspaces-David/{id}/`, then:\n\n```bash\ncd Wadspaces-David\n./build.sh --only {id}          # add --kalebrowser-local to use ../KaleBrowser\n```\n\n## Run\n\nOn a WadSpaces machine, \"Install on this machine\" in Wad Creator adds it to\n`/etc/wadspaces/workspaces.yaml`. By hand, add `workspaces.yaml.snippet` to\nthat file, or use `wad-{id}.container` directly as a quadlet.\n\nTo try it without the switcher:\n\n```bash\n{run}\n```\n{secrets_note}",
        name = js::field(spec, "name"),
        features = or_none(features.join(", ")),
        projects = or_none(js::join_field(js::arr(spec, "projects"), "name", ", ")),
        webapps = or_none(js::join_field(js::arr(spec, "webapps"), "name", ", ")),
        kale = or_none(js::join_field(js::arr(spec, "kaleResources"), "app_name", ", ")),
        display = if host { "on the machine's screen (remote: stream sidecar)" } else { "streamed" },
        remote = if host { " (remote run only)" } else { "" },
    )
}

/// One file of the build folder.
pub enum Content {
    Text(String),
    Bytes(Vec<u8>),
}

/// The build folder. `dockerfile_text` replaces the generated Dockerfile (a hand edit).
pub fn bundle_files(spec: &Value, wallpaper: Option<&[u8]>, dockerfile_text: Option<&str>) -> Vec<(String, Content)> {
    let w = to_wadd_spec(spec);
    let id = js::field(spec, "id");
    let mut files = vec![
        (
            "Dockerfile".to_string(),
            Content::Text(dockerfile_text.map(String::from).unwrap_or_else(|| dockerfile(spec))),
        ),
        ("docker-compose.yml".into(), Content::Text(compose(spec))),
        ("README.md".into(), Content::Text(readme(spec))),
        (format!("wad-{id}.container"), Content::Text(quadlet(&w, PROJECTS_DIR, STATE_DIR, None))),
        ("workspaces.yaml.snippet".into(), Content::Text(workspaces_yaml_snippet(&w))),
    ];
    if spec.get("layout").is_some_and(js::truthy) {
        files.push(("root/etc/wadspaces/layout.json".into(), Content::Text(layout_json(spec))));
    }
    if !js::arr(spec, "kaleResources").is_empty() {
        files.push(("root/etc/wadspaces/kalebrowser-resources.json".into(), Content::Text(kale_resources_json(spec))));
    }
    if let (Some(wp), Some(bytes)) = (spec.get("wallpaper").filter(|w| js::truthy(w)), wallpaper) {
        files.push((
            format!("root/usr/share/backgrounds/{}", js::field(wp, "fileName")),
            Content::Bytes(bytes.to_vec()),
        ));
    }
    files
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    #[test]
    fn rootless_units_match_the_python_wadd() {
        let w = json!({
            "id": "writing", "name": "Writing", "image": "localhost/wadspaces-writing:latest", "display": "host",
            "env": {"PUID": "1000", "TZ": "Pacific/Fiji"}, "secrets": ["github_token"], "devices": ["/dev/dri"],
            "shm_size": "1g", "projects": [{"id": "p1", "mount": "Notes"}],
        });
        let got =
            super::quadlet(&w, "/home/u/.local/share/wadspaces-projects", "/home/u/.local/state/wadspaces", Some(1000));
        assert_eq!(got, include_str!("../../../fixtures/quadlet/wad-writing-rootless.container"));
    }
}
