"""Configuration: /etc/wadspaces/workspaces.yaml.

The YAML file is the single source of truth for which workspaces exist, their
order, ports and hotkeys. Runtime state comes from podman.
"""
from __future__ import annotations

import logging
import os
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import yaml

ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}$")
# Projects (wadd/projects.py) mounted into a workspace: ids are Firestore
# auto-ids (20 alphanumerics) or ones wadd made the same way; the mount is the
# folder's name on the workspace's Desktop. The image checks both again.
PROJECT_ID_RE = re.compile(r"^[A-Za-z0-9_-]{1,64}$")
MOUNT_RE = re.compile(r"^[A-Za-z0-9._-]{1,64}$")
# A folder or drive project is mounted from its own host path (Volume=<path>:…).
# podman splits a volume on ':', and systemd expands '%' specifiers in a unit,
# so neither may be in one; nor quotes, backslashes or control characters.
HOST_PATH_BAD_RE = re.compile(r"[:%\\\"'\x00-\x1f\x7f]")
BACKENDS = ("systemd", "podman")
PREFETCH = ("autostart", "all", "none")
# stream: the desktop is streamed to a frame in the kiosk (an all-in-one
#         Selkies image publishing a port).
# host:   the desktop draws on this machine's own screen as its own window
#         (a lean image from containers/_common); no port, no stream. The same
#         image runs remotely next to the stream sidecar (containers/_stream).
DISPLAYS = ("stream", "host")
SYSTEMD_SCOPES = ("system", "user")
# Which cloud project this machine belongs to ships with the host image, not
# in workspaces.yaml: bootc keeps a locally changed /etc file on update (and
# wadd rewrites workspaces.yaml whenever a workspace changes), so a project set
# there would never move. /usr is replaced on every update. Its keys win over
# the YAML's cloud section.
VENDOR_CLOUD = Path("/usr/lib/wadspaces/cloud.yaml")
# Keys older wadds wrote into workspaces.yaml (save_config writes every field)
# whose features are gone. bootc keeps that file across updates, so they are
# dropped on load rather than rejected as unknown. Can go after one release.
DEPRECATED = {
    "daemon": {"base_registry"},
    "cloud": {"storage_bucket", "storage_base", "files_every_s"},
}

# Daemon keys newer than the host images out there: config_to_dict leaves
# them out while they have their default (see there).
NEWER_DAEMON_KEYS = ("projects_dir", "projects_uid", "tailscale_socket", "tailscale_bin",
                     "tailnet_streams", "folder_roots")
# Where folder projects (and the folder browser) may be: home folders and
# where drives are mounted. A folder must be strictly inside one of them.
FOLDER_ROOTS = ["/var/home", "/home", "/mnt", "/media", "/run/media", "/run/wadspaces-drives"]

log = logging.getLogger(__name__)


class ConfigError(ValueError):
    pass


@dataclass
class WorkspaceSpec:
    id: str
    name: str
    image: str
    port: int | None = None
    hotkey: int | None = None
    icon: str | None = None
    enabled: bool = True
    container_name: str = ""
    container_port: int = 3000
    env: dict[str, str] = field(default_factory=dict)
    secrets: list[str] = field(default_factory=list)
    volumes: list[str] = field(default_factory=list)
    devices: list[str] = field(default_factory=list)
    shm_size: str | None = "1g"
    # started by wadd once images are pulled after boot (not a quadlet
    # [Install]: a boot-time pull of several GB would hit systemd timeouts)
    autostart: bool = False
    display: str = "stream"
    # Project folders mounted read-write at ~/Desktop/<mount>, as
    # [{"id": <project id>, "mount": <folder name>, "path"?: <host path>}]; set
    # by a launch. path: a folder or drive project's own folder (a git
    # project's is <projects_dir>/<id>).
    projects: list[dict] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not self.container_name:
            self.container_name = f"wad-{self.id}"

    @property
    def native(self) -> bool:
        return self.display == "host"

    @property
    def url(self) -> str | None:
        """Where the stream answers; None for a native workspace."""
        return None if self.native or self.port is None else f"http://127.0.0.1:{self.port}/"

    @property
    def unit(self) -> str:
        """systemd unit generated by quadlet from wad-<id>.container."""
        return f"wad-{self.id}.service"


@dataclass
class KeysConfig:
    """Keyboard handling (wadd/keyproxy.py). wadd grabs the keyboards and keeps
    Super for itself: Super+Tab switcher, Super+1..9 jump, `launcher` keys
    (with Super) go home. `block` chords are dropped before they reach the
    kiosk, e.g. "alt+f4"; modifiers match exactly."""
    enabled: bool = True
    launcher: list[str] = field(default_factory=lambda: ["KEY_0", "KEY_SPACE"])
    block: list[str] = field(default_factory=lambda: ["alt+f4", "ctrl+shift+q", "ctrl+alt+backspace"])
    pass_super: bool = False  # also send Super chords on to the workspace
    grab: bool = True         # False: only watch for chords, filter nothing


@dataclass
class DaemonConfig:
    bind: str = "127.0.0.1"
    port: int = 8080
    backend: str = "systemd"
    systemd_scope: str = "system"
    podman_socket: str = "/run/podman/podman.sock"
    cdp_url: str = "http://127.0.0.1:9222"
    keys: KeysConfig = field(default_factory=KeysConfig)
    ready_timeout_s: int = 600
    # where CRUD writes wad-<id>.container units (systemd backend only)
    quadlet_dir: str = "/etc/containers/systemd"
    # baked into the image by host/build.sh; each file in podman/ becomes a
    # podman secret of the same name (re-seeded when the file changes)
    secrets_dir: str = "/usr/lib/wadspaces/secrets"
    state_dir: str = "/var/lib/wadspaces"
    # what to download once the network is up: "none" (download from the
    # launcher or on first switch), "autostart" (just the workspaces that
    # start at boot) or "all". "all" and "autostart" skip an image when less
    # than prefetch_min_free_gb is left, so small disks don't fill up.
    prefetch: str = "none"
    prefetch_min_free_gb: int = 15
    # images downloaded at once (Home starts every pick's download together)
    max_parallel_pulls: int = 3
    # Building images on the machine (Wad Creator's Build): refuse to start
    # with less free disk than this.
    build_min_free_gb: int = 8
    # Project folders, one per project (<projects_dir>/<id>). Not under
    # state_dir, which is root-only: they belong to projects_uid, the uid of
    # abc in the workspace images (PUID 1000, the kiosk user `wad` on the
    # host), so the container can write them.
    projects_dir: str = "/var/lib/wadspaces-projects"
    projects_uid: int = 1000
    # Tailscale, the trusted network (wadd/tailnet.py): tailscaled's LocalAPI
    # socket and the CLI. Without them (a dev laptop) the tailnet is just
    # reported as not installed. tailnet_streams: serve running stream
    # workspaces on the tailnet (`tailscale serve`, HTTPS, never Funnel).
    tailscale_socket: str = "/run/tailscale/tailscaled.sock"
    tailscale_bin: str = "tailscale"
    tailnet_streams: bool = True
    # Folder projects and the folder browser stay inside these (FOLDER_ROOTS).
    folder_roots: list[str] = field(default_factory=lambda: list(FOLDER_ROOTS))

    @property
    def base_url(self) -> str:
        host = "127.0.0.1" if self.bind in ("0.0.0.0", "::") else self.bind
        return f"http://{host}:{self.port}"


@dataclass
class LauncherConfig:
    # Wad Creator's desktop app, started in the kiosk session as a window of
    # its own (a view "app:wadcreator"). Without sway (dev) Home falls back to
    # showing wadcreator_url in the shell.
    wadcreator_app: str = "/usr/lib/wadcreator/wadcreator"
    wadcreator_url: str = "http://localhost:8081/"
    allow_navigate: list[str] = field(default_factory=list)


@dataclass
class ShellConfig:
    """The kiosk page: it keeps each workspace in its own frame so switching
    is instant. Only the most recently used live_frames stay loaded; the rest
    are dropped and reconnect (about a second) when you come back."""
    live_frames: int = 3


@dataclass
class WadCreatorConfig:
    """Wad Creator served locally by wadd from a built dist/ (temporary: it
    will move to wadcreator.com, talking to wadd through the cloud relay)."""
    enabled: bool = True
    bind: str = "127.0.0.1"
    port: int = 8081
    dist: str = "/usr/share/wadspaces/wadcreator"


@dataclass
class CloudConfig:
    project_id: str
    functions_region: str = "australia-southeast2"  # where enrollMachine is deployed
    api_key: str = ""
    state_file: str = "/var/lib/wadspaces/enrollment.json"
    functions_base: str = ""  # override, e.g. the emulator
    firestore_base: str = ""  # override, e.g. the emulator
    heartbeat_s: int = 30
    poll_s: int = 3

    @property
    def functions_url(self) -> str:
        return self.functions_base or f"https://{self.functions_region}-{self.project_id}.cloudfunctions.net"

    @property
    def firestore_url(self) -> str:
        base = self.firestore_base or "https://firestore.googleapis.com/v1"
        return f"{base}/projects/{self.project_id}/databases/(default)/documents"


@dataclass
class Config:
    machine_name: str
    daemon: DaemonConfig
    launcher: LauncherConfig
    cloud: CloudConfig | None
    workspaces: list[WorkspaceSpec]
    path: Path | None = None
    wadcreator: WadCreatorConfig = field(default_factory=WadCreatorConfig)
    shell: ShellConfig = field(default_factory=ShellConfig)

    def workspace(self, ws_id: str) -> WorkspaceSpec:
        for ws in self.workspaces:
            if ws.id == ws_id:
                return ws
        raise KeyError(ws_id)

    def workspace_or_none(self, ws_id: str) -> WorkspaceSpec | None:
        try:
            return self.workspace(ws_id)
        except KeyError:
            return None

    def by_hotkey(self, n: int) -> WorkspaceSpec | None:
        for ws in self.workspaces:
            if ws.enabled and ws.hotkey == n:
                return ws
        return None

    @property
    def enabled_workspaces(self) -> list[WorkspaceSpec]:
        return [ws for ws in self.workspaces if ws.enabled]


def _pick(data: dict, cls, name: str) -> dict:
    """Keep only keys the dataclass knows; unknown keys are a config error."""
    known = set(cls.__dataclass_fields__)
    unknown = set(data) - known
    if unknown:
        raise ConfigError(f"{name}: unknown keys {sorted(unknown)}")
    return data


def _drop_deprecated(data: dict, section: str) -> dict:
    out = dict(data.get(section) or {})
    for key in DEPRECATED[section] & set(out):
        log.debug("%s.%s is no longer used; ignoring it", section, key)
        del out[key]
    return out


def parse_config(data: dict[str, Any], path: Path | None = None) -> Config:
    if not isinstance(data, dict):
        raise ConfigError("config must be a mapping")
    version = data.get("version", 1)
    if version != 1:
        raise ConfigError(f"unsupported config version {version}")

    machine = data.get("machine") or {}
    machine_name = str(machine.get("name") or "wadspaces")

    d = _drop_deprecated(data, "daemon")
    # `hotkeys` is the old name for `keys` (enabled + launcher only).
    raw_keys = {**dict(d.pop("hotkeys", None) or {}), **dict(d.pop("keys", None) or {})}
    keys = KeysConfig(**_pick(raw_keys, KeysConfig, "daemon.keys"))
    from .keyproxy import Chord, keycode  # noqa: PLC0415 - avoids a cycle at import
    try:
        for chord in keys.block:
            Chord.parse(chord)
        for name in keys.launcher:
            keycode(name)
    except ValueError as e:
        raise ConfigError(f"daemon.keys: {e}") from e
    daemon = DaemonConfig(keys=keys, **_pick(d, DaemonConfig, "daemon"))
    if daemon.backend not in BACKENDS:
        raise ConfigError(f"daemon.backend must be one of {BACKENDS}")
    if daemon.systemd_scope not in SYSTEMD_SCOPES:
        raise ConfigError(f"daemon.systemd_scope must be one of {SYSTEMD_SCOPES}")
    if daemon.prefetch not in PREFETCH:
        raise ConfigError(f"daemon.prefetch must be one of {PREFETCH}")
    if daemon.max_parallel_pulls < 1:
        raise ConfigError("daemon.max_parallel_pulls must be at least 1")

    launcher = LauncherConfig(**_pick(dict(data.get("launcher") or {}), LauncherConfig, "launcher"))

    wadcreator = WadCreatorConfig(**_pick(dict(data.get("wadcreator") or {}), WadCreatorConfig, "wadcreator"))

    shell = ShellConfig(**_pick(dict(data.get("shell") or {}), ShellConfig, "shell"))
    if shell.live_frames < 1:
        raise ConfigError("shell.live_frames must be at least 1")

    cloud = None
    if data.get("cloud"):
        c = _pick(_drop_deprecated(data, "cloud"), CloudConfig, "cloud")
        if not c.get("project_id"):
            raise ConfigError("cloud.project_id is required when cloud is set")
        cloud = CloudConfig(**c)

    workspaces: list[WorkspaceSpec] = []
    seen_ids, seen_ports, seen_hotkeys, seen_names = set(), set(), set(), set()
    for i, raw in enumerate(data.get("workspaces") or []):
        where = f"workspaces[{i}]"
        raw = dict(_pick(dict(raw), WorkspaceSpec, where))
        for req in ("id", "name", "image"):
            if req not in raw:
                raise ConfigError(f"{where}: missing {req}")
        if raw.get("display", "stream") not in DISPLAYS:
            raise ConfigError(f"{where}: display must be one of {DISPLAYS}")
        if raw.get("display", "stream") == "stream" and raw.get("port") is None:
            raise ConfigError(f"{where}: missing port (a streamed workspace needs one)")
        raw["env"] = {str(k): str(v) for k, v in (raw.get("env") or {}).items()}
        ws = WorkspaceSpec(**raw)
        where = f"workspace {ws.id!r}"
        if not ID_RE.match(ws.id):
            raise ConfigError(f"{where}: id must match {ID_RE.pattern}")
        if ws.id in seen_ids:
            raise ConfigError(f"{where}: duplicate id")
        if ws.port is not None:
            if not (1 <= int(ws.port) <= 65535):
                raise ConfigError(f"{where}: port out of range")
            if ws.port in seen_ports or ws.port == daemon.port or (wadcreator.enabled and ws.port == wadcreator.port):
                raise ConfigError(f"{where}: port {ws.port} already used")
            seen_ports.add(ws.port)
        if ws.container_name in seen_names:
            raise ConfigError(f"{where}: duplicate container_name")
        _check_projects(ws, where)
        if ws.hotkey is not None:
            if not (1 <= int(ws.hotkey) <= 9):
                raise ConfigError(f"{where}: hotkey must be 1..9")
            if ws.enabled and ws.hotkey in seen_hotkeys:
                raise ConfigError(f"{where}: hotkey {ws.hotkey} already used")
            if ws.enabled:
                seen_hotkeys.add(ws.hotkey)
        seen_ids.add(ws.id)
        seen_names.add(ws.container_name)
        workspaces.append(ws)

    return Config(machine_name=machine_name, daemon=daemon, launcher=launcher,
                  cloud=cloud, workspaces=workspaces, path=path, wadcreator=wadcreator,
                  shell=shell)


def _check_projects(ws: WorkspaceSpec, where: str) -> None:
    if not isinstance(ws.projects, list):
        raise ConfigError(f"{where}: projects must be a list")
    ids, mounts = set(), set()
    for p in ws.projects:
        if not isinstance(p, dict) or set(p) not in ({"id", "mount"}, {"id", "mount", "path"}):
            raise ConfigError(f"{where}: each project is {{id, mount, path?}}, not {p!r}")
        pid, mount = str(p["id"]), str(p["mount"])
        if "path" in p:
            path = p["path"]
            if not isinstance(path, str) or not path.startswith("/") or HOST_PATH_BAD_RE.search(path):
                raise ConfigError(f"{where}: project path {path!r} must be absolute, without ':' or '%'")
        if not PROJECT_ID_RE.match(pid):
            raise ConfigError(f"{where}: project id {pid!r} must match {PROJECT_ID_RE.pattern}")
        if not MOUNT_RE.match(mount) or mount in (".", ".."):
            raise ConfigError(f"{where}: project mount {mount!r} must match {MOUNT_RE.pattern}")
        if pid in ids:
            raise ConfigError(f"{where}: project {pid} is listed twice")
        if mount in mounts:
            raise ConfigError(f"{where}: two projects are mounted at Desktop/{mount}")
        ids.add(pid)
        mounts.add(mount)


def workspace_to_dict(ws: WorkspaceSpec) -> dict:
    d = asdict(ws)
    if d["container_name"] == f"wad-{ws.id}":
        del d["container_name"]
    if d["container_port"] == 3000:
        del d["container_port"]
    if not d["autostart"]:
        del d["autostart"]
    if d["display"] == "stream":
        del d["display"]
    return {k: v for k, v in d.items() if v not in (None, [], {})}


def config_to_dict(cfg: Config) -> dict:
    daemon = asdict(cfg.daemon)
    # Newer keys are only written when changed, so the file still loads in the
    # wadd of the image before (bootc rollback), which rejects unknown keys.
    for key in NEWER_DAEMON_KEYS:
        f = DaemonConfig.__dataclass_fields__[key]
        default = f.default_factory() if callable(f.default_factory) else f.default
        if daemon[key] == default:
            del daemon[key]
    out: dict[str, Any] = {
        "version": 1,
        "machine": {"name": cfg.machine_name},
        "daemon": daemon,
        "launcher": asdict(cfg.launcher),
        "wadcreator": asdict(cfg.wadcreator),
        "shell": asdict(cfg.shell),
    }
    if cfg.cloud:
        out["cloud"] = asdict(cfg.cloud)
    out["workspaces"] = [workspace_to_dict(ws) for ws in cfg.workspaces]
    return out


def save_config(cfg: Config, path: str | Path | None = None) -> Path:
    """Atomically rewrite the YAML (comments are not preserved)."""
    path = Path(path or cfg.path)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text("# Managed by wadd; edits through Wad Creator rewrite this file.\n"
                   + yaml.safe_dump(config_to_dict(cfg), sort_keys=False), encoding="utf-8")
    os.replace(tmp, path)
    return path


def load_config(path: str | Path, vendor_cloud: str | Path | None = VENDOR_CLOUD) -> Config:
    path = Path(path)
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except FileNotFoundError as e:
        raise ConfigError(f"config not found: {path}") from e
    except yaml.YAMLError as e:
        raise ConfigError(f"{path}: {e}") from e
    if vendor_cloud:
        try:
            vendor = yaml.safe_load(Path(vendor_cloud).read_text(encoding="utf-8")) or {}
        except FileNotFoundError:
            vendor = {}
        except yaml.YAMLError as e:
            raise ConfigError(f"{vendor_cloud}: {e}") from e
        if vendor:
            data["cloud"] = {**(data.get("cloud") or {}), **vendor}
    return parse_config(data, path)
