//! The cutover from the Python wadd (`wadd migrate`): a machine's old
//! workspaces.yaml, its generated units and its baked token, with the
//! image's workspaces on top.

mod common;

use common::Fake;
use sha2::{Digest, Sha256};
use wad_config::{Config, Profile};
use wadd::migrate;

const YAML: &str = r#"
version: 1
daemon:
  quadlet_dir: QUADLETS
workspaces:
  - id: writing
    name: Writing
    image: ghcr.io/hunggod/wadspaces-cosmic-bodybuilding:latest
    display: stream
    port: 3100
    hotkey: 1
  - id: mine
    name: Built here
    image: localhost/wadspaces-mine:latest
    display: host
    hotkey: 7
    projects: [{id: p1, mount: notes}]
"#;

/// The image's Writing is a native window now (the Surface's stale /etc
/// still had it streamed).
const VENDOR_WRITING: &str = r#"
name = "Writing"
image = "ghcr.io/hunggod/wadspaces-cosmic-bodybuilding:latest"
display = "host"
hotkey = 1
"#;

struct Env {
    _d: tempfile::TempDir,
    cfg: Config,
    etc_units: std::path::PathBuf,
    fake: Fake,
}

fn env(baked: &str, token: Option<&str>) -> Env {
    let d = tempfile::tempdir().unwrap();
    let p = d.path();
    let etc_units = p.join("etc-units");
    for dir in ["state", "etc-units", "run-units", "vendor"] {
        std::fs::create_dir_all(p.join(dir)).unwrap();
    }
    std::fs::write(p.join("workspaces.yaml"), YAML.replace("QUADLETS", etc_units.to_str().unwrap())).unwrap();
    std::fs::write(
        etc_units.join("wad-writing.container"),
        "# Generated by `wadd gen-quadlets` from workspaces.yaml. Do not edit.\n[Container]\n",
    )
    .unwrap();
    std::fs::write(etc_units.join("wad-handmade.container"), "[Container]\n").unwrap();
    std::fs::write(p.join("vendor/writing.toml"), VENDOR_WRITING).unwrap();
    let digest: String = Sha256::digest(baked.as_bytes()).iter().map(|b| format!("{b:02x}")).collect();
    std::fs::write(p.join("state/seeded-secrets.json"), format!("{{\"github_token\": \"{digest}\"}}")).unwrap();
    let fake = Fake::default();
    if let Some(t) = token {
        fake.with(|m| {
            m.secrets.insert("github_token".into(), t.as_bytes().to_vec());
        });
    }
    let mut cfg = Config::defaults(Profile::User);
    cfg.daemon.state_dir = p.join("state");
    cfg.daemon.legacy_config = p.join("workspaces.yaml");
    cfg.daemon.vendor_workspaces = p.join("vendor");
    cfg.daemon.units_dir = p.join("run-units");
    Env { _d: d, cfg, etc_units, fake }
}

#[tokio::test]
async fn moves_a_python_machine_over_once() {
    let e = env("ghp_baked\n", Some("ghp_baked"));
    let report = migrate::apply(&e.cfg, Some(&e.fake), false).await.unwrap();
    let text = report.join("\n");
    assert!(text.contains("workspaces: 2"), "{text}");
    assert!(text.contains("removed 1"), "{text}");
    assert!(text.contains("removed the baked GitHub token"), "{text}");

    // The list is state now, with the image's Writing applied and the
    // machine's own workspace (and its projects) kept.
    let (list, from_yaml) = wadd::own_workspaces(&e.cfg.daemon).unwrap();
    assert!(!from_yaml);
    let writing = list.iter().find(|w| w.id == "writing").unwrap();
    assert_eq!(writing.display, wad_proto::v1::Display::Host);
    let mine = list.iter().find(|w| w.id == "mine").unwrap();
    assert_eq!(mine.projects[0].id, "p1");
    // Only the units the Python wadd wrote are gone; the YAML stays (unused).
    assert!(!e.etc_units.join("wad-writing.container").exists());
    assert!(e.etc_units.join("wad-handmade.container").exists());
    assert!(e.cfg.daemon.legacy_config.exists());
    assert!(!e.fake.0.lock().unwrap().secrets.contains_key("github_token"));

    // Done once: the next start leaves everything be.
    e.fake.with(|m| {
        m.secrets.insert("github_token".into(), b"ghp_baked".to_vec());
    });
    let again = migrate::apply(&e.cfg, Some(&e.fake), false).await.unwrap();
    assert!(again[0].starts_with("already done"), "{again:?}");
    assert!(e.fake.0.lock().unwrap().secrets.contains_key("github_token"));
}

#[tokio::test]
async fn keeps_a_token_the_machine_signed_in_for() {
    let e = env("ghp_baked\n", Some("gho_signed_in"));
    let report = migrate::apply(&e.cfg, Some(&e.fake), false).await.unwrap();
    assert!(report.iter().any(|l| l.contains("machine's own; kept")), "{report:?}");
    assert!(e.fake.0.lock().unwrap().secrets.contains_key("github_token"));
}

#[tokio::test]
async fn without_podman_it_tries_again_next_time() {
    let e = env("ghp_baked\n", Some("ghp_baked"));
    let report = migrate::apply(&e.cfg, None, false).await.unwrap();
    assert!(report.iter().any(|l| l.contains("isn't reachable")), "{report:?}");
    assert!(!e.cfg.daemon.state_dir.join(migrate::MARKER).exists());
    let report = migrate::apply(&e.cfg, Some(&e.fake), false).await.unwrap();
    assert!(report.iter().any(|l| l.contains("removed the baked")), "{report:?}");
}

#[test]
fn a_new_machine_gets_the_images_workspaces() {
    let e = env("x", None);
    std::fs::remove_file(&e.cfg.daemon.legacy_config).unwrap();
    let list = wadd::read_workspaces(&e.cfg.daemon, false).unwrap();
    assert_eq!(list.iter().map(|w| w.id.as_str()).collect::<Vec<_>>(), ["writing"]);
    // Saved, and not applied twice.
    assert!(e.cfg.daemon.state_dir.join("workspaces.json").exists());
    let book = wad_store::vendor::read_book(&e.cfg.daemon.state_dir);
    assert!(book.contains_key("writing"));
}

#[test]
fn icons_come_only_from_the_icon_folders() {
    let d = tempfile::tempdir().unwrap();
    let own = d.path().join("state/icons");
    std::fs::create_dir_all(&own).unwrap();
    std::fs::write(own.join("w.png"), b"\x89PNG").unwrap();
    std::fs::write(own.join("w.txt"), b"text").unwrap();
    std::fs::write(d.path().join("secret.png"), b"x").unwrap();
    std::os::unix::fs::symlink(d.path().join("secret.png"), own.join("escape.png")).unwrap();
    let icon = |p: &str| wadd::api::icon_file(&own.join(p), &own).map(|(m, b)| (m, b.len()));
    assert_eq!(icon("w.png"), Some(("image/png", 4)));
    assert_eq!(icon("w.txt"), None); // not a picture
    assert_eq!(icon("escape.png"), None); // points outside
    assert_eq!(wadd::api::icon_file(&d.path().join("secret.png"), &own), None);
    assert_eq!(wadd::api::icon_file(std::path::Path::new("/etc/passwd"), &own), None);
}
