//! The cutover from the Python wadd (`wadd migrate`, which wadd.service runs
//! before each start with full privileges; it does nothing once done).
//! wad_store::migrate::plan says what it would do; this does it:
//!
//! - the workspace list becomes state (workspaces.json, from the old
//!   workspaces.yaml), with the image's workspaces applied over it;
//! - the units the Python wadd generated into /etc/containers/systemd go
//!   (the Rust wadd writes its own to /run at every start);
//! - the GitHub token the old images baked in goes, if it's still that one
//!   (it's revoked: the machine signs in to GitHub instead).
//!
//! Everything else stays as it is, in the formats the Python wadd reads, so
//! `bootc rollback` still finds it. (A rollback boots the old image's own
//! /etc, with its workspaces.yaml and units.)

use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};
use wad_config::Config;

use crate::backend::Backend;

/// Written once the migration is done.
pub const MARKER: &str = "migrated-from-python";
/// What the Python wadd put at the top of each unit it wrote.
const PY_HEADER: &str = "# Generated by `wadd gen-quadlets`";

/// What was done, one line per step.
pub type Report = Vec<String>;

/// Runs the migration (again, when `force`). Every step is safe to repeat.
pub async fn apply(cfg: &Config, backend: Option<&dyn Backend>, force: bool) -> Result<Report, String> {
    let d = &cfg.daemon;
    let marker = d.state_dir.join(MARKER);
    if marker.exists() && !force {
        return Ok(vec![format!("already done ({})", marker.display())]);
    }
    let mut report = Report::new();

    let (_, from_yaml) = crate::own_workspaces(d)?;
    let list = crate::read_workspaces(d, true)?;
    let ids: Vec<&str> = list.iter().map(|w| w.id.as_str()).collect();
    report.push(format!(
        "workspaces: {} in {} ({}){}",
        list.len(),
        d.state_dir.join("workspaces.json").display(),
        ids.join(", "),
        if from_yaml { format!(", from {}", d.legacy_config.display()) } else { String::new() }
    ));

    let old_units = legacy_units_dir(cfg);
    match old_units {
        Some(dir) => {
            let removed = remove_python_units(&dir, &d.units_dir)?;
            report.push(format!("units: removed {} from {}", removed.len(), dir.display()));
        }
        None => report.push("units: no old units".into()),
    }

    match backend {
        Some(b) => report.push(reset_baked_token(&d.state_dir, b).await?),
        None => report.push("secrets: podman isn't reachable; the baked token check is left for next time".into()),
    }

    // Without podman the token check is still to do: not done yet.
    if backend.is_some() {
        let at = crate::now_secs();
        std::fs::write(&marker, format!("{at} wadd {}\n", env!("CARGO_PKG_VERSION")))
            .map_err(|e| format!("{}: {e}", marker.display()))?;
    }
    Ok(report)
}

/// Where the Python wadd wrote its units (its workspaces.yaml says), if
/// that's somewhere else than where the Rust wadd writes its own.
fn legacy_units_dir(cfg: &Config) -> Option<PathBuf> {
    let d = &cfg.daemon;
    let dir = match wad_store::legacy::read(&d.legacy_config, None) {
        Ok(c) => PathBuf::from(c.quadlet_dir()),
        // No old config: where the Python wadd's always were, on a machine.
        Err(_) if cfg.daemon.units_dir == Path::new("/run/containers/systemd") => "/etc/containers/systemd".into(),
        Err(_) => return None,
    };
    (dir != d.units_dir && dir.is_dir()).then_some(dir)
}

/// Removes the `wad-*.container` units the Python wadd generated in `dir`
/// (only those: anything else there was put there by hand). The names gone.
pub fn remove_python_units(dir: &Path, own: &Path) -> Result<Vec<String>, String> {
    if dir == own {
        return Ok(vec![]);
    }
    let mut removed = Vec::new();
    let entries = match std::fs::read_dir(dir) {
        Ok(rd) => rd,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(removed),
        Err(e) => return Err(format!("{}: {e}", dir.display())),
    };
    for e in entries.filter_map(|e| e.ok()) {
        let name = e.file_name().to_string_lossy().into_owned();
        if !(name.starts_with("wad-") && name.ends_with(".container")) {
            continue;
        }
        let ours = std::fs::read_to_string(e.path()).is_ok_and(|t| t.starts_with(PY_HEADER));
        if ours {
            std::fs::remove_file(e.path()).map_err(|err| format!("{}: {err}", e.path().display()))?;
            removed.push(name);
        }
    }
    removed.sort();
    Ok(removed)
}

/// The Python wadd seeded github_token from a token baked into old images
/// (seeded-secrets.json has the digest). If podman's is still that one, it
/// goes: it's revoked, and a refused token reads as "signed in" until used.
pub async fn reset_baked_token(state_dir: &Path, backend: &dyn Backend) -> Result<String, String> {
    let seeded = wad_store::State::new(state_dir).seeded_digest("github_token");
    let Some(baked) = seeded else { return Ok("secrets: no baked GitHub token".into()) };
    let Some(token) = backend.github_token().await else { return Ok("secrets: no GitHub token here".into()) };
    let hex = |b: &[u8]| Sha256::digest(b).iter().map(|x| format!("{x:02x}")).collect::<String>();
    // podman's value is read trimmed; the baked file may have ended in a newline.
    if hex(token.as_bytes()) == baked || hex(format!("{token}\n").as_bytes()) == baked {
        backend.delete_secret("github_token").await?;
        Ok("secrets: removed the baked GitHub token (sign in to GitHub from WadSpaces)".into())
    } else {
        Ok("secrets: the GitHub token is the machine's own; kept".into())
    }
}
